config/routes.rb
SourcedPartx::Engine.routes.draw do
  
  resources :parts do
    collection do
      get :search
      get :search_results
      get :stats
      get :stats_results    
    end
#=begin    
    workflow_routes = Authentify::AuthentifyUtility.find_config_const('part_wf_route', 'sourced_partx')
    if Authentify::AuthentifyUtility.find_config_const('wf_route_in_config') == 'true' && workflow_routes.present?
      eval(workflow_routes) 
    elsif Rails.env.test?
      member do
        get :event_action
        patch :submit
        patch :manager_approve
        patch :manager_reject
        patch :vp_approve
        patch :vp_reject
        patch :vp_rewind
        patch :stamp
        patch :complete
      end
      
      collection do
        get :list_open_process
      end
    end
#=end
  end
  
  root :to => 'parts#index'
end

app/models/sourced_partx/part.rb
module SourcedPartx
  include Authentify::AuthentifyUtility
  require 'workflow'
  class Part < ActiveRecord::Base
    include Workflow
    workflow_column :wf_state
    
    workflow do
      #self.to_s = 'EngineName::TableName'    ex, 'InQuotex::Quote'
      wf = Authentify::AuthentifyUtility.find_config_const('part_wf_pdef', 'sourced_partx')
      if Authentify::AuthentifyUtility.find_config_const('wf_pdef_in_config') == 'true' && wf.present?
         #quotes is table name
        eval(wf) # if wf.present? #&& self.wf_state.present? 
      elsif Rails.env.test?  
        state :initial_state do
          event :submit, :transitions_to => :manager_reviewing
        end
        state :manager_reviewing do
          event :manager_approve, :transitions_to => :vp_reviewing
          event :manager_reject, :transitions_to => :fresh
        end
        state :vp_reviewing do
          event :vp_approve, :transitions_to => :approved
          event :vp_reject, :transitions_to => :rejected
          event :vp_rewind, :transitions_to => :initial_state
        end
        state :approved do
          event :stamp, :transitions_to => :stamped
        end
        state :stamped do
          event :complete, :transitions_to => :completed
        end
        state :completed
        state :rejected
      end
    end
    
    attr_accessor :void_nopudate, :status_name, :src_eng_name, :project_name, :plant_name, :last_updated_by_name, :requested_by_name, :completed_noupdate, :id_noupdate, 
                  :wf_comment, :customer_name, :wf_state_noupdate, :wf_event
=begin
    attr_accessible :finish_date, :last_updated_by_id, :name, :part_num, :plant_id, :project_id, :qty, :part_spec, :src_eng_id, :start_date, :wf_state, 
                    :status_id, :unit, :unit_price, :void, :customer_id, :shipping_cost, :tax, :total, :misc_cost, :total, :brief_note, :completed,
                    :requested_by_id, :approved, :approved_date, :approved_by_id,
                    :customer_name, :project_name,
                    :as => :role_new
    attr_accessible :finish_date, :last_updated_by_id, :name, :part_num, :plant_id, :project_id, :qty, :part_spec, :src_eng_id, :start_date, :wf_state, 
                    :status_id, :unit, :unit_price, :void, :customer_id, :shipping_cost, :tax, :total, :misc_cost, :total, :brief_note, :requested_by_id,
                    :completed, :total_audited, :approved, :approved_date, :approved_by_id,
                    :void_nopudate, :status_name, :src_eng_name, :project_name, :plant_name, :last_updated_by_name, :completed_noupdate, :requested_by_name,
                    :id_noupdate, :wf_comment, :customer_name, :wf_state_noupdate, 
                    :as => :role_update
    
    attr_accessor   :project_id_s, :start_date_s, :end_date_s, :purchasing_id_s, :customer_id_s, :eng_id_s, :name_s, :part_spec_s, :part_num_s, 
                    :plant_id_s, :delivered_s, :time_frame_s, :keyword_s, :status_id_s, :requested_by_id_s, :manufacturer_id_s

    attr_accessible :project_id_s, :start_date_s, :end_date_s, :purchasing_id_s, :customer_id_s, :eng_id_s, :status_id_s, :manufacturer_id_s,
                    :plant_id_s, :delivered_s, :keyword_s, :requested_by_id_s, :name_s, :part_spec_s, :part_num_s, :as => :role_search_stats
=end
                                    
    belongs_to :project, :class_name => SourcedPartx.project_class.to_s
    belongs_to :src_eng, :class_name => 'Authentify::User'
    belongs_to :plant, :class_name => SourcedPartx.plant_class.to_s
    belongs_to :status, :class_name => 'Commonx::MiscDefinition'
    belongs_to :last_updated_by, :class_name => 'Authentify::User'
    belongs_to :requested_by, :class_name => 'Authentify::User'
    belongs_to :approved_by, :class_name => 'Authentify::User'
    belongs_to :customer, :class_name => SourcedPartx.customer_class.to_s

    validates :name, :presence => true, :uniqueness => {:scope => :project_id, :case_sensitive => false, :message => I18n.t('Duplicate Sourcing Part Name') }
    validates :part_spec, :unit, :presence => true 
    validates :project_id, :qty, :requested_by_id, :customer_id, :presence => true,
                           :numericality => {:greater_than => 0, :only_integer => true}
    validates :unit_price, :numericality => {:if => 'unit_price.present?'}
    validates :total, :numericality => { :if => 'total.present?' } 
    validates :approved_by_id, :numericality => {:greater_than => 0, :only_integer => true}, :if => 'approved_by_id.present?'
    validate :dynamic_validate
    
    #for workflow input validation  
    validate :validate_wf_input_data, :if => 'wf_state.present?' 
    
    def validate_wf_input_data
      wf = Authentify::AuthentifyUtility.find_config_const('validate_part_' + self.wf_event, 'sourced_partx') if self.wf_event.present?
      if Authentify::AuthentifyUtility.find_config_const('wf_validate_in_config') == 'true' && wf.present? 
        eval(wf) 
      end
    end
    
    def dynamic_validate
      wf = Authentify::AuthentifyUtility.find_config_const('dynamic_validate', 'sourced_partx')
      eval(wf) if wf.present?
    end
    
  end
end

app/controllers/sourced_partx/application_controller.rb
module SourcedPartx
  class ApplicationController < ::ApplicationController
    include Authentify::SessionsHelper
    include Authentify::AuthentifyUtility
    include Authentify::UsersHelper
    include Authentify::UserPrivilegeHelper
    include Commonx::CommonxHelper
    include Searchx::SearchHelper
    include BizWorkflowx::WfHelper
    
    before_action :require_signin
    before_action :max_pagination 
    before_action :check_access_right 
    before_action :load_session_variable, :only => [:new, :edit]  #for parent_record_id & parent_resource in check_access_right
    after_action :delete_session_variable, :only => [:create, :update]   #for parent_record_id & parent_resource in check_access_right
    before_action :view_in_config?
    
    protected
  
    def max_pagination
      @max_pagination = find_config_const('pagination')
    end
    
    def view_in_config?
      @view_in_config = Authentify::AuthentifyUtility.load_view_in_config
    end
    
    #engine's
    def return_customers_by_access_right     
      access_rights, model_ar_r, has_record_access = access_right_finder('index', SourcedPartx.customer_class.to_s.underscore.pluralize)
      return [] if access_rights.blank?
      return model_ar_r #instance_eval(access_rights.sql_code) #.present?
    end
    
    def return_projects_by_access_right     
      access_rights, model_ar_r, has_record_access = access_right_finder('index', SourcedPartx.project_class.to_s.underscore.pluralize)
      return [] if access_rights.blank?
      return model_ar_r #instance_eval(access_rights.sql_code) #.present?
    end

  end
end

app/controllers/sourced_partx/parts_controller.rb
require_dependency "sourced_partx/application_controller"

module SourcedPartx
  class PartsController < ApplicationController
    before_action :require_employee
    before_action :load_parent_record
    
    def index
      @title = 'Sourcing Parts'      
      @parts = params[:sourced_partx_parts][:model_ar_r]
      @parts = @parts.where(:customer_id => @customer.id) if @customer
      @parts = @parts.where(:project_id => @project.id) if @project
      @parts = @parts.page(params[:page]).per_page(@max_pagination)
      @erb_code = find_config_const('part_index_view', 'sourced_partx')
    end
  
    def new
      @title = 'New Sourcing Part'
      @part = SourcedPartx::Part.new
      @qty_unit = find_config_const('piece_unit').split(',').map(&:strip)
      @erb_code = find_config_const('part_new_view', 'sourced_partx')
    end
  
    def create
      @part = SourcedPartx::Part.new(new_params)
      @part.last_updated_by_id = session[:user_id]
      @part.requested_by_id = session[:user_id]
      if @part.save
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Saved!")
      else
        @project = SourcedPartx.project_class.find_by_id(params[:part][:project_id]) if params[:part].present? && params[:part][:project_id].present?
        @customer = SourcedPartx.customer_class.find_by_id(params[:part][:customer_id]) if params[:part].present? && params[:part][:customer_id].present?
        @qty_unit = find_config_const('piece_unit').split(',').map(&:strip)
        @erb_code = find_config_const('part_new_view', 'sourced_partx')
        flash.now[:error] = t('Data Error. Not Saved!')
        render 'new'
      end
    end
  
    def edit
      @title = 'Edit Sourcing Part'
      @part = SourcedPartx::Part.find_by_id(params[:id])
      @qty_unit = find_config_const('piece_unit').split(',').map(&:strip)
      @erb_code = find_config_const('part_edit_view', 'sourced_partx')
      if @part.wf_state.present? && @part.current_state != :initial_state
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=NO Update. Record Being Processed!")
      end
    end
  
    def update
      @part = SourcedPartx::Part.find_by_id(params[:id])
      @part.last_updated_by_id = session[:user_id]
      if @part.update_attributes(edit_params)
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Updated!")
      else
        @erb_code = find_config_const('part_edit_view', 'sourced_partx')
        @qty_unit = find_config_const('piece_unit').split(',').map(&:strip)
        flash.now[:error] = t('Data Error. Not Updated!')
        render 'edit'
      end
    end
  
    def show
      @title = 'Sourcing Part Info'
      @part = SourcedPartx::Part.find_by_id(params[:id])
      @erb_code = find_config_const('part_show_view', 'sourced_partx')
    end
    
    def list_open_process  
      index()
      @parts = return_open_process(@parts, find_config_const('part_wf_final_state_string', 'sourced_partx'))  #
    end
    
    protected
    def load_parent_record
      @customer = SourcedPartx.customer_class.find_by_id(params[:customer_id]) if params[:customer_id].present?
      @project = SourcedPartx.project_class.find_by_id(params[:project_id]) if params[:project_id].present?
      @customer = SourcedPartx.customer_class.find_by_id(@project.customer_id) if params[:project_id].present?
      @project = SourcedPartx.project_class.find_by_id(SourcedPartx::Part.find_by_id(params[:id]).project_id) if params[:id].present?
      @customer = SourcedPartx.customer_class.find_by_id(SourcedPartx::Part.find_by_id(params[:id]).customer_id) if params[:id].present?
    end
    
    private
    
    def new_params
      params.require(:part).permit(:finish_date, :last_updated_by_id, :name, :part_num, :plant_id, :project_id, :qty, :part_spec, :src_eng_id, :start_date, :wf_state, 
                    :status_id, :unit, :unit_price, :void, :customer_id, :shipping_cost, :tax, :total, :misc_cost, :total, :brief_note, :completed,
                    :requested_by_id)
    end
    
    def edit_params
      params.require(:part).permit(:finish_date, :name, :part_num, :plant_id, :project_id, :qty, :part_spec, :src_eng_id, :start_date, :wf_state, 
                    :status_id, :unit, :unit_price, :void, :customer_id, :shipping_cost, :tax, :total, :misc_cost, :total, :brief_note, :requested_by_id,
                    :completed, :total_audited, :approved, :approved_date, :approved_by_id)
    end
    
  end
end

app/helpers/sourced_partx/application_helper.rb
module SourcedPartx
  module ApplicationHelper
  end
end

app/helpers/sourced_partx/parts_helper.rb
module SourcedPartx
  module PartsHelper
  end
end

app/views/sourced_partx/parts/_form.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
  
  <% else %>
  <%=t(@title)%>
<%= simple_form_for @part do |f| %> 

  <%= f.input :customer_name, :label => t('Customer'), :readonly => true, :input_html => {:value => @customer.name} %>
  <%= f.input :project_name, :label => t('Project Name'), :readonly => true, :input_html => {:value => @project.name} %>
  <%= f.input :name, :label => t('Part Name'), :readonly => readonly?(@part, 'name') %>  
  <%= f.input :part_num, :label => t('Part#'), :readonly => readonly?(@part, 'part_num') %>
  <%= f.input :part_spec, :label => t('Spec'), :input_html => {:rows => 2}, :readonly => readonly?(@part, 'part_spec') %>
  <%= f.input :qty, :label => t('Qty'), :readonly => readonly?(@part, 'qty') %>
  <%= f.input :unit, :label => t('Qty Unit'), :collection => @qty_unit, :readonly => readonly?(@part, 'unit') %>
  <%= f.input :unit_price, :label => t('Unit Price($)'), :readonly => readonly?(@part, 'unit_price') %>
  <%= f.input :shipping_cost, :label => t('Shipping Cost($)'), :readonly => readonly?(@part, 'shipping_cost') %>
  <%= f.input :tax, :label => t('Tax($)'), :readonly => readonly?(@part, 'tax') %>
  <%= f.input :misc_cost, :label => t('Misc Cost($)'), :readonly => readonly?(@part, 'misc_cost') %>
  <%= f.input :total, :label => t('Total($)'), :readonly => true %>
  <%= f.input :start_date, :label => t('Start Date'), :as => :string, :readonly => readonly?(@part, 'start_date') %>
  <%= f.input :finish_date, :label => t('Finish Date'), :as => :string, :readonly => readonly?(@part, 'finish_date') %>
  <%= f.input :completed, :label => t("Completed?"), :as => :boolean unless readonly?(@part, 'completed') %>
  <%= f.input :completed_noupdate, :label => t("Completed?"), :readonly => true, :input_html => {:value => @part.received ? t('Yes') : t('No') } if readonly?(@part, 'completed') %>
  <%= f.input :status_id, :label => t('Sourcing Status'), :collection => Commonx::MiscDefinition.where(:for_which => 'part_sourcing_status') unless readonly?(@part, 'status_id') %>
  <%= f.input :status_id, :label => t('Sourcing Status'), :readonly => true, :input_html => {:value => @part.status.name} if readonly?(@part, 'status_id') %>
  <%= f.input :src_eng_id, :label => t('Sourcing Eng'), :collection => Authentify::User.where(:status => 'active'), :include_blank => true unless readonly?(@part, 'src_eng_id') %>
  <%= f.input :src_eng_name, :label => t('Sourcing Eng'), :input_html => {:value => @part.src_eng.name} if @part.src_eng_id.present? && readonly?(@part, 'src_eng_id') %>
  <%= f.input :plant_id, :label => t('Sourcing Plant'), :collection => SrcPlantx::Plant.where(:active => true).order('id') unless readonly?(@part, 'plant_id') %>
  <%= f.input :plant_name, :label => t('Sourcing Plant'), :input_html => {:value => @part.plant.name} if @part.plant_id.present? && readonly?(@part, 'plant_id') %>
  <%= f.input :void_noupdate, :label => t('Void'), :readonly => true, :required => false, :input_html => {:value => @part.void} if readonly?(@part, 'void') %>
  <%= f.input :void, :label => t('Void'), :input_html => {:value => @part.void} unless readonly?(@part, 'void') %>
  <%= f.input :requested_by_name, :label => t('Requested By'), :readonly => true, :input_html => {:value => @part.requested_by.name} %>
  <%= f.input :brief_note, :label => t('Brief Note'), :readonly => readonly?(@part, 'brief_note'), :input_html => {:rows => 2} %>
    
  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %>  

<% end %>

app/views/sourced_partx/parts/_form_list.html.erb
 <% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
  <% else %>
<div class="pagination"><%= will_paginate models %></div>
   <%=t(@title)%>
    <table class="table table-striped">
		<tr>
			<th>#</th>
			<th><%= t('Project Name') %></th>
			<th><%= t('Customer') %></th>
			<th><%= t('Part Name') %></th>
			<th><%= t('Part#') %></th>
			<th><%= t('Spec') %></th>
			<th><%= t('Qty/Unit') %></th>
			<th><%= t('Unit Price($)') %></th>
			<th><%= t('Total($)') %></th>			
		    <th><%= t('Total Audited($)') %></th>
			<th><%= t('Created Date') %></th>
			<th><%= t('Src Plant') %></th>
			<th><%= t('Void') %></th>
			<th><%= t('Start Date') %></th>
			<th><%= t('Finish Date') %></th>
			<th><%= t('Complted') %></th>
			<th><%= t('Sourcing Eng') %></th>
			<th><%= t('Requested By') %></th>
			<th><%= t('WF State') %></th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
		<% models.each do |r| %>
		  <tr>
		  	<% unless has_action_right?('show', params[:controller], r) %>
		  	  <td><%= prt(r, :id) %></td>
		  	<% else %>
		  	  <td><%= link_to r.id.to_s, SUBURI + "/authentify/view_handler?index=1&url=#{part_path(r)}" %></td>
		  	<% end %>
		  	<% unless has_action_right?('show', SourcedPartx.project_class.to_s.underscore.pluralize) %>
		  	  <td><%= prt(r, 'project.name') %></td>
		  	<% else %>
		  	  <td><%= link_to r.project.name, SUBURI + "/authentify/view_handler?index=1&url=#{SUBURI + CGI::escape(eval(SourcedPartx.show_project_path))}" %></td>
		  	<% end %>
		  	<% unless has_action_right?('show', SourcedPartx.customer_class.to_s.underscore.pluralize) %>
		  	  <td><%= prt(r, 'customer.name') %></td>
		  	<% else %>
		  	  <td><%= link_to r.customer.short_name, SUBURI + "/authentify/view_handler?index=1&url=#{SUBURI + CGI::escape(eval(SourcedPartx.show_customer_path))}" %></td>
		  	<% end %>
		  	<td><%= prt(r, :name) %></td>
			<td><%= prt(r, :part_num) %></td>
			<td><%= prt(r, :part_spec) %></td>
			<td><%= prt(r, :qty) %>/<%= prt(r, :unit) %></td>
			<td><%= prt(r, :unit_price) %></td>
			<td><%= prt(r, :total) %></td>
			<td><%= r.created_at.strftime("%Y/%m/%d") %></td>
			<% unless has_action_right?('show', SourcedPartx.plant_class.to_s.underscore.pluralize) %>
		  	  <td><%= prt(r, 'plant.short_name') if r.plant_id.present? %></td>
		  	<% else %>
		  	  <td><%= link_to r.plant.short_name, SUBURI + "/authentify/view_handler?index=1&url=#{SUBURI + CGI::escape(eval(SourcedPartx.show_plant_path))}" if r.plant_id.present? %></td>
		  	<% end %>
		  	<td><%= t(prt(r, :void).to_s) %></td>
			<td><%= r.start_date.strftime("%Y/%m/%d") if r.start_date.present? %></td>
			<td><%= r.finish_date.strftime("%Y/%m/%d") if r.finish_date.present? %></td>
			<td><%= r.completed ? t('Yes') : t('No') %></td>
			<td><%= prt(r, 'src_eng.name') if r.src_eng_id.present? %></td> 
			<td><%= prt(r, 'requested_by.name') %></td> 
			<td><%= t(prt(r, :wf_state).humanize.titleize) if r.wf_state.present? %></td>  
			<td><%= link_to t('Submit Sourcing'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI.escape event_action_part_path(r, :wf_event => 'submit', :resource_id => r.id, :resource_string => params[:controller])}", :class => BUTTONS_CLS['action']  if r.wf_state.present? && r.wf_state == 'initial_state' && has_action_right?('submit', params[:controller], r) %></td>
			<td><%= link_to t('Manager ') + t('Approve'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI.escape event_action_part_path(r, :wf_event => 'manager_approve', :resource_id => r.id, :resource_string => params[:controller])}", :class => BUTTONS_CLS['action']  if r.wf_state.present? && r.wf_state == 'manager_reviewing' && has_action_right?('manager_approve', params[:controller], r) %></td>
			<td><%= link_to t('Manager ') + t('Reject'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI.escape event_action_part_path(r, :wf_event => 'manager_reject', :resource_id => r.id, :resource_string => params[:controller])}", :class => BUTTONS_CLS['action']  if r.wf_state.present? && r.wf_state == 'manager_reviewing' && has_action_right?('manager_reject', params[:controller], r) %></td>
			<td><%= link_to t('VP ') + t('Approve'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI.escape event_action_part_path(r, :wf_event => 'vp_approve', :resource_id => r.id, :resource_string => params[:controller])}", :class => BUTTONS_CLS['action']  if r.wf_state.present? && r.wf_state == 'vp_reviewing' && has_action_right?('vp_approve', params[:controller], r) %></td>
			<td><%= link_to t('VP ') + t('Reject'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI.escape event_action_part_path(r, :wf_event => 'vp_reject', :resource_id => r.id, :resource_string => params[:controller])}", :class => BUTTONS_CLS['action']  if r.wf_state.present? && r.wf_state == 'vp_reviewing' && has_action_right?('vp_reject', params[:controller], r) %></td>
		    <td><%= link_to t('VP ') + t('Rewind'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI.escape event_action_part_path(r, :wf_event => 'vp_rewind', :resource_id => r.id, :resource_string => params[:controller])}", :class => BUTTONS_CLS['action']  if r.wf_state.present? && r.wf_state == 'vp_reviewing' && has_action_right?('vp_rewind', params[:controller], r) %></td>
		    <td><%= link_to t('Stamp'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI.escape event_action_part_path(r, :wf_event => 'stamp', :resource_id => r.id, :resource_string => params[:controller])}", :class => BUTTONS_CLS['action']  if r.wf_state.present? && r.wf_state == 'approved' && has_action_right?('stamp', params[:controller], r) %></td>
		    <td><%= link_to t('Complete'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI.escape event_action_part_path(r, :wf_event => 'complete', :resource_id => r.id, :resource_string => params[:controller])}", :class => BUTTONS_CLS['action']  if r.wf_state.present? && r.wf_state == 'stamped' && has_action_right?('complete', params[:controller], r) %></td>
		    <td><%= link_to t('Edit'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI.escape edit_part_path(r, :parent_record_id => r.project_id, :parent_resource => SourcedPartx.project_class.to_s.underscore.pluralize)}", :class => BUTTONS_CLS['action']  if (r.wf_state.nil? or r.wf_state == 'initial_state') && has_action_right?('update', params[:controller], r) %></td>
			<td><%= link_to t('Payment Requests'), SUBURI + "/authentify/view_handler?index=1&url=#{SUBURI + CGI.escape(eval(SourcedPartx.index_payment_request_path.to_s))}", :class => BUTTONS_CLS['action']  if has_action_right?('index', SourcedPartx.payment_request_resource.to_s) %></td>
			<td><%= link_to t('Payment Requests'), SUBURI + "/authentify/view_handler?index=1&url=#{SUBURI + CGI.escape(eval(SourcedPartx.index_payment_request_sourced_partx_path.to_s))}", :class => BUTTONS_CLS['action']  if has_action_right?('index_sourced_partx', SourcedPartx.payment_request_resource.to_s) %></td>
		  </tr>
		<% end %>
	</table>
	
	<table class="table table-striped">
	  <tr>
	    <th>
	    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	    	<%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action']  %>
	    	<%= link_to t('New Sourcing'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI.escape new_part_path(:project_id => @project.id, :parent_record_id => @project.id, :parent_resource => SourcedPartx.project_class.to_s.underscore.pluralize)}", :class => BUTTONS_CLS['action']  if @project && has_action_right?('update', params[:controller], @project) %>
	    	<%= link_to t('Open Process'), SUBURI + "/authentify/view_handler?index=1&url=#{list_open_process_parts_path(:project_id => @project.id, :parent_record_id => @project.id, :parent_resource => SourcedPartx.project_class.to_s.underscore.pluralize)}", :class => BUTTONS_CLS['action']  if @project && has_action_right?('list_open_process', params[:controller], @project) %>
	    	<%= link_to t('Open Process'), SUBURI + "/authentify/view_handler?index=1&url=#{list_open_process_parts_path}", :class => BUTTONS_CLS['action']  if @project.nil? && has_action_right?('list_open_process', params[:controller], @project) %>
	    
	    </th>
	  </tr>
	</table>
	
	<% end %>
	

app/views/sourced_partx/parts/create.html.erb
<h4>Projects#create</h4>
<p>Find me in app/views/task_definitions/create.html.erb</p>

app/views/sourced_partx/parts/edit.html.erb
 
<%= render 'form'  %>
 

  
 

app/views/sourced_partx/parts/index.html.erb
 
	<%= render partial: 'form_list', locals: {models: @parts} %>
 

app/views/sourced_partx/parts/list_open_process.html.erb
<div id="main_body">
	<h4><%=t('Sourcing Parts') %></h>
 
	<%= render partial: 'form_list', locals: {models: @parts} %>
 
</div>

app/views/sourced_partx/parts/new.html.erb
<%= render 'form_new' %>

app/views/sourced_partx/parts/update.html.erb
<h1>EventTasks#update</h1>
<p>Find me in app/views/event_taskx/event_tasks/update.html.erb</p>